### ISSUE TITLE
Unit tests no more passes

### ISSUE THREAD

**Issue by tizbecool** [johnpaulett/txHL7#9]
Hi,

I try to run the unit tests with trial and their not passing:

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/tmp/twisted-hl7/tests/test_mllp.py", line 59, in testParseMessage
    self.protocol.transport.write.call_args[0][0]))
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'

tests.test_mllp.MinimalLowerLayerProtocolTest.testParseMessage
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/tmp/twisted-hl7/tests/test_mllp.py", line 80, in testParseMessageUnicode
    self.protocol.transport.write.call_args[0][0]))
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'

tests.test_mllp.MinimalLowerLayerProtocolTest.testParseMessageUnicode
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/tmp/twisted-hl7/tests/test_mllp.py", line 69, in testUncaughtError
    self.protocol.transport.write.call_args[0][0]))
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'

tests.test_mllp.MinimalLowerLayerProtocolTest.testUncaughtError
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/tmp/twisted-hl7/twistedhl7/mllp.py", line 49, in onError
    reject = message_container.ack(ack_code='AR')
  File "/tmp/twisted-hl7/tests/test_mllp.py", line 28, in ack
    return unicode(self.message.create_ack(ack_code, message_id=ACK_ID))
exceptions.AttributeError: 'Message' object has no attribute 'create_ack'

<not in test>
<not in test>
<not in test>
-------------------------------------------------------------------------------
Ran 5 tests in 0.032s

FAILED (errors=6, successes=2)

**Comment by johnpaulett** [comment]
I'm unable to reproduce using a fresh checkout.  We had some major changes in the past several months -- package renamed and python-hl7 upgraded  (which had backwards-incompatible changes).

It would appear that the old package name is still referenced in this run ("twistedhl7" should be txHL7 now in: `File "/tmp/twisted-hl7/twistedhl7/mllp.py", line 49, in onError`).  Can you ensure that you have the latest git checkout, update the virtualenv (`make env`, can blow away the `env` folder and have it recreated if needed)?

**Comment by tizbecool** [comment]
Ok, I'm so confused ... It's a RTFM manual case ... I just forgot to run the "make env" after I update my old fork.

Thank you Paul and sorry for the disturd...

**Comment by johnpaulett** [comment]
@tizbecool, no problem!  Ideally the Makefile should see the dependency change when `make tests` is run (since it transitively depends on requirements.txt) -- if not, there may be a slight bug in the Makefile I created.

**Comment by tizbecool** [comment]
`make tests`is fine, I ran `trial tests` directly :)
